services:
  - type: web
    name: selfrank
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: RENDER
        value: "true"
